/*

Copyright (C) 2013-2016, Securifera, Inc 

All rights reserved. 

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
	this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright notice,
	this list of conditions and the following disclaimer in the documentation 
	and/or other materials provided with the distribution.

    * Neither the name of Securifera, Inc nor the names of its contributors may be 
	used to endorse or promote products derived from this software without specific
	prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS 
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

================================================================================

The copyright on this package is held by Securifera, Inc

*/

/*
 * SettingsJDialog.java
 *
 */

package rsrc_edit.settings;

import java.awt.Cursor;
import java.awt.event.WindowEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JDialog;
import rsrc_edit.MainJFrame;

/**
 *
 *  
 */
public class SettingsJDialog extends JDialog {
    
    private final SettingsJDialogListener theListener;
    private static final String NAME_Class = SettingsJDialog.class.getSimpleName();
 
    //=======================================================================
    /** Creates new form SettingsJDialog
     * @param parent
     * @param modal */
    public SettingsJDialog( SettingsJDialogListener parent, boolean modal ) {
       super( parent.getParentJFrame() , modal);
       
       theListener = parent;
     
       initComponents();
       initializeComponents();
       setLocationRelativeTo(null);

    }//End Constructor

     //=======================================================================
    /**
     * Initializes all the components
    */
    private void initializeComponents(){
        
        xorKeyValue.setVisible(false);
        xorKeyLabel.setVisible(false);
        
        //encodingButtonGroup.add(base64Button);
        encodingButtonGroup.add( asciiSpacerButton);
        encodingButtonGroup.add( noneButton);
        encodingButtonGroup.add( xorButton);
        
        MainJFrame parentFrame = theListener.getParentJFrame();
        if( parentFrame != null ){
            Settings theSettings = parentFrame.getSettings();
            String encoding = theSettings.getDefaultStringEncoding();
            
            Enumeration<AbstractButton> buttons = encodingButtonGroup.getElements();
            while( buttons.hasMoreElements()){
                AbstractButton aButton = buttons.nextElement();
                if( aButton.getText().equals(encoding) ){
                    aButton.setSelected(true);
                    break;
                }
            }
        }
              
    }

    /**
    * Sets the save button enablement
     * @param passedBool
    */
    public void setSaveButton(boolean passedBool){
        if(passedBool)
            saveOrOkJButton.setText("Save");
        else
            saveOrOkJButton.setText("OK");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encodingButtonGroup = new javax.swing.ButtonGroup();
        cancelJButton = new javax.swing.JButton();
        saveOrOkJButton = new javax.swing.JButton();
        encodingPanel = new javax.swing.JPanel();
        asciiSpacerButton = new javax.swing.JRadioButton();
        noneButton = new javax.swing.JRadioButton();
        xorButton = new javax.swing.JRadioButton();
        xorKeyValue = new javax.swing.JTextField();
        xorKeyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setModal(true);
        setName("Options"); // NOI18N

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        saveOrOkJButton.setText("OK");
        saveOrOkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveOrOkJButtonActionPerformed(evt);
            }
        });

        encodingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Default String Encoding"));

        asciiSpacerButton.setText("Byte Spacer");
        asciiSpacerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asciiSpacerButtonActionPerformed(evt);
            }
        });

        noneButton.setText("None");
        noneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneButtonActionPerformed(evt);
            }
        });

        xorButton.setText("XOR");
        xorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xorButtonActionPerformed(evt);
            }
        });

        xorKeyLabel.setText("Key (Hex):");

        javax.swing.GroupLayout encodingPanelLayout = new javax.swing.GroupLayout(encodingPanel);
        encodingPanel.setLayout(encodingPanelLayout);
        encodingPanelLayout.setHorizontalGroup(
            encodingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encodingPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(encodingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encodingPanelLayout.createSequentialGroup()
                        .addComponent(xorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(xorKeyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xorKeyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(noneButton)
                    .addComponent(asciiSpacerButton))
                .addContainerGap())
        );
        encodingPanelLayout.setVerticalGroup(
            encodingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encodingPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(noneButton)
                .addGap(3, 3, 3)
                .addComponent(asciiSpacerButton)
                .addGap(3, 3, 3)
                .addGroup(encodingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(xorKeyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xorKeyLabel))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 258, Short.MAX_VALUE)
                        .addComponent(saveOrOkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cancelJButton))
                    .addComponent(encodingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encodingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveOrOkJButton)
                    .addComponent(cancelJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
       closeDialog();
   }//GEN-LAST:event_cancelJButtonActionPerformed

   private void saveOrOkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveOrOkJButtonActionPerformed

        String buttonText = saveOrOkJButton.getText();

        if(buttonText.equals("Save")){
            
            setCursor( Cursor.getPredefinedCursor( Cursor.WAIT_CURSOR ) );
            
            MainJFrame parentFrame = theListener.getParentJFrame();
            if( parentFrame != null ){
                Settings theSettings = parentFrame.getSettings();
                for (Enumeration<AbstractButton> buttons = encodingButtonGroup.getElements(); buttons.hasMoreElements();) {
                    AbstractButton button = buttons.nextElement();

                    //Set and save
                    if (button.isSelected()) {
                        String encoding = button.getText();
                        theSettings.setDefaultStringEncoding(encoding);
                        parentFrame.saveSettings();
                    }
                }
               
            }
                        
            try {
                setSaveButton(false);
            } finally {
                setCursor(null);
            }

        } else
            closeDialog();
        
   }//GEN-LAST:event_saveOrOkJButtonActionPerformed

    private void asciiSpacerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asciiSpacerButtonActionPerformed
        setSaveButton(true);
        xorKeyValue.setVisible(false);
        xorKeyLabel.setVisible(false);
    }//GEN-LAST:event_asciiSpacerButtonActionPerformed

    private void noneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneButtonActionPerformed
        setSaveButton(true);
        xorKeyValue.setVisible(false);
        xorKeyLabel.setVisible(false);
    }//GEN-LAST:event_noneButtonActionPerformed

    private void xorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xorButtonActionPerformed
        setSaveButton(true);
        xorKeyValue.setVisible(true);
        xorKeyLabel.setVisible(true);
    }//GEN-LAST:event_xorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton asciiSpacerButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.ButtonGroup encodingButtonGroup;
    private javax.swing.JPanel encodingPanel;
    private javax.swing.JRadioButton noneButton;
    private javax.swing.JButton saveOrOkJButton;
    private javax.swing.JRadioButton xorButton;
    private javax.swing.JLabel xorKeyLabel;
    private javax.swing.JTextField xorKeyValue;
    // End of variables declaration//GEN-END:variables

    //========================================================================
    /**
     * Get the listener
     * @return 
     */
    public SettingsJDialogListener getDialogListener() {
        return theListener;
    }

    // ==========================================================================
    /**
    * Processes {@link WindowEvent}s occurring on this component.
    * <p>
    * This method is overridden to handle unsaved changes when the window is closed
    * using the X(exit) button and give the user the option of cancelling the close.
    *
    * @param event the {@code WindowEvent}
    */
    @Override //Overrides JFrame.processWindowEvent( WindowEvent )
    protected void processWindowEvent( WindowEvent event ) {

        if( WindowEvent.WINDOW_CLOSING == event.getID() )
            closeDialog();            
        else
            super.processWindowEvent( event );

    }
    
    // ==========================================================================
    /**
    *   Handles the logic necessary before the dialog is closed
    */
    private void closeDialog() {               
                
        dispose();

    }

}
