/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsrc_edit;

import java.awt.Cursor;
import java.util.Arrays;
import rsrc_edit.codec.Codec;
import rsrc_edit.resource.ResourceDataEntry;

/**
 *
 * @author user
 */
public class BinaryResourceJPanel extends javax.swing.JPanel {

    private final ResourceController theResourceController;
    /**
     * Creates new form BinaryResourceJPanel
     * @param passedController
     */
    public BinaryResourceJPanel( ResourceController passedController ) {
        initComponents();
        theResourceController = passedController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getDataButton = new javax.swing.JButton();
        setDataButton = new javax.swing.JButton();
        dataScrollPane = new javax.swing.JScrollPane();
        dataTextArea = new javax.swing.JTextArea();

        getDataButton.setText("View Data");
        getDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDataButtonActionPerformed(evt);
            }
        });

        setDataButton.setText("Set Data");

        dataTextArea.setEditable(false);
        dataTextArea.setColumns(20);
        dataTextArea.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        dataTextArea.setLineWrap(true);
        dataTextArea.setRows(5);
        dataScrollPane.setViewportView(dataTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(68, 158, Short.MAX_VALUE)
                        .addComponent(getDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setDataButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getDataButton)
                    .addComponent(setDataButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDataButtonActionPerformed
      
        setCursor( Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR) );
        dataTextArea.setText("");
        
        ResourceDataEntry aRDE = theResourceController.getObject();
        String retStr = Utilities.byteArrayToHex( aRDE.data );
        dataTextArea.append(retStr);
        repaint();
        
        setCursor( null );
    }//GEN-LAST:event_getDataButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane dataScrollPane;
    private javax.swing.JTextArea dataTextArea;
    private javax.swing.JButton getDataButton;
    private javax.swing.JButton setDataButton;
    // End of variables declaration//GEN-END:variables

    //========================================================================
    /**
     * 
     * @param passedCodec 
     */
    public void encodingChanged( Codec passedCodec ) {    
           
        ResourceDataEntry aRDE =  theResourceController.getObject();
        if( aRDE.data[0] != 0x0 || aRDE.data[1] != 0x0){
            byte[] bytes = Arrays.copyOfRange(aRDE.data, 0, aRDE.data.length);
            byte[] decoded = passedCodec.decode(bytes);
            String retStr = Utilities.byteArrayToHex( decoded );
            dataTextArea.setText( retStr );
        } 
    }   

}
