/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsrc_edit;

import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rsrc_edit.codec.Codec;
import rsrc_edit.resource.ResourceDataEntry;
import rsrc_edit.settings.Settings;

/**
 *
 * @author user
 */
public class StringResourceJPanel extends javax.swing.JPanel implements Codecable {

    private final ResourceController theResourceController;
    private boolean labelChanged = false;
  
    /**
     * Creates new form StringResourceJPanel
     * @param passedController
     */
    public StringResourceJPanel( ResourceController passedController ) {
        initComponents();
        theResourceController = passedController;
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        valueLabelField = new javax.swing.JTextField();
        getDataButton = new javax.swing.JButton();
        setDataButton = new javax.swing.JButton();

        valueLabelField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valueLabelField.setText("< Undefined >");
        valueLabelField.setBorder(null);
        valueLabelField.setOpaque(false);
        valueLabelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueLabelFieldKeyReleased(evt);
            }
        });

        getDataButton.setText("View Data");
        getDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDataButtonActionPerformed(evt);
            }
        });

        setDataButton.setText("Set Data");
        setDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valueLabelField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(getDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setDataButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(valueLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(valueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getDataButton)
                    .addComponent(setDataButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valueLabelFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueLabelFieldKeyReleased
        labelChanged = true;
    }//GEN-LAST:event_valueLabelFieldKeyReleased

    private void getDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDataButtonActionPerformed
        MainJFrame aFrame = theResourceController.getParentFrame();
        encodingChanged(aFrame.getSelectedCodec());
    }//GEN-LAST:event_getDataButtonActionPerformed

    private void setDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDataButtonActionPerformed
        ResourceDataEntry aRDE = theResourceController.getObject();
        File binFile = theResourceController.getParentFrame().getLoadedFile();
        if( binFile != null ){
            
            //Don't count the string size and id fields
            int availSpace = (int) (aRDE.Size);
            
            FileOutputStream aFOS = null;
            FileChannel currentBinaryFileChannel = null;
                          

            String userString = valueJTextField.getText();

            //Get selected encoding
            MainJFrame aFrame = theResourceController.getParentFrame();
            Codec curCodec = aFrame.getSelectedCodec();
            byte[] value = curCodec.encode(userString.getBytes());
            userString = new String(value);               

            if( userString.length() > 0 ){
                byte[] strBytes;
                try {
                    strBytes = userString.getBytes("UTF-16LE");
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(StringResourceJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
                
                if( strBytes.length > aRDE.Size ){
                    JOptionPane.showMessageDialog( this, "Length of the provided string is too long.","Error", JOptionPane.ERROR_MESSAGE );
                } else {

                    //Pad the buffer up to the available size
                    strBytes = Arrays.copyOf(strBytes, availSpace);
                    //Copy to object data
                    System.arraycopy(strBytes, 0, aRDE.data, 0, availSpace);
                    try { 
                        //Open file
                        aFOS = new FileOutputStream(binFile, true);
                        currentBinaryFileChannel = aFOS.getChannel();

                        //Write to the file
                        ByteBuffer aBB = ByteBuffer.wrap(strBytes);
                        currentBinaryFileChannel.write(aBB, aRDE.DataVirtualAddr + aRDE.Embedded_Write_Delta);


                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(StringResourceJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(StringResourceJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            if(currentBinaryFileChannel != null )
                                currentBinaryFileChannel.close();
                        } catch (IOException ex) {
                        }
                    }
                }
            }   
            
        }
        
        //Change the value for the label
        if( labelChanged ){            
            //Get the label value
            String labelVal = valueLabelField.getText();
            String stringId = aRDE.toString();
            
            //Add to settings
            Settings theSettings = theResourceController.getParentFrame().getSettings();
            theSettings.setStringForId(stringId, labelVal);
            
            //Save
            theResourceController.getParentFrame().saveSettings();
            labelChanged = false;
        }
    }//GEN-LAST:event_setDataButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getDataButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton setDataButton;
    private javax.swing.JTextField valueJTextField;
    private javax.swing.JTextField valueLabelField;
    // End of variables declaration//GEN-END:variables

    private void initializeComponents() {
        
        MainJFrame aFrame = theResourceController.getParentFrame();
        Settings appSettings = aFrame.getSettings();
        
        String idStr = theResourceController.toString();
        String actualStr = appSettings.getStringForId(idStr);
        if( actualStr != null ){
            valueLabelField.setText(actualStr);
        }
        
        //Set current encoding
        Codec curCodec = aFrame.getSelectedCodec();
        encodingChanged(curCodec);
        
    }
    
    //========================================================================
    /**
     * 
     * @param passedCodec 
     */
    @Override
    public void encodingChanged( Codec passedCodec ) {    
           
        ResourceDataEntry aRDE =  theResourceController.getObject();
        if( aRDE.data[0] != 0x0 || aRDE.data[1] != 0x0){
            byte[] unicodebytes = Arrays.copyOfRange(aRDE.data, 0, aRDE.data.length - 8);
            byte[] asciibytes = Utilities.unicodeToAscii(unicodebytes);
            byte[] decoded = passedCodec.decode(asciibytes);
            valueJTextField.setText(new String(decoded).trim());
        } 
    }       
}
